/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.HospedagemController;
import controller.ClienteController;
import controller.FuncionarioController;
import controller.QuartoController;
import java.awt.Dimension;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import persistence.ClientePersistence;
import persistence.FuncionarioPersistence;
import persistence.HospedagemPersistence;
import persistence.Persistence;
import persistence.QuartoPersistence;

/**
 *
 * @author lucas
 */
public class Principal extends javax.swing.JFrame {

    private static ClienteController cliente;
    private static FuncionarioController funcionario;

    

    /**
     * Creates new form Principal
     */
    public Principal() {
        this.setCliente(new ClienteController());
        this.setFuncionario(new FuncionarioController());
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
         this.setExtendedState(MAXIMIZED_BOTH);  
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jCadastro = new javax.swing.JMenu();
        jCadastroQuartos = new javax.swing.JMenuItem();
        jCadastroClientes = new javax.swing.JMenuItem();
        jCadastroFuncionarios = new javax.swing.JMenuItem();
        jAlterar = new javax.swing.JMenu();
        jAlterarQuartos = new javax.swing.JMenuItem();
        jAlterarClientes = new javax.swing.JMenuItem();
        jAlterarFuncionarios = new javax.swing.JMenuItem();
        jRemover = new javax.swing.JMenu();
        jRemoverQuartos = new javax.swing.JMenuItem();
        jRemoverClientes = new javax.swing.JMenuItem();
        jRemoverFuncionarios = new javax.swing.JMenuItem();
        jListar = new javax.swing.JMenu();
        jListarQuartos = new javax.swing.JMenuItem();
        jListarClientes = new javax.swing.JMenuItem();
        jListarFuncionarios = new javax.swing.JMenuItem();
        jQuartosVazios = new javax.swing.JMenuItem();
        jQuartoOcupado = new javax.swing.JMenuItem();
        jListaCheckIn = new javax.swing.JMenuItem();
        jCheckin = new javax.swing.JMenu();
        jCheckout = new javax.swing.JMenu();
        jSobre = new javax.swing.JMenu();
        jSair = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setTitle("Sistema de Automoção Hoteleira(SIAH)");

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N

        jCadastro.setText("Cadastro");
        jCadastro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jCadastroQuartos.setText("Quartos");
        jCadastroQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroQuartosActionPerformed(evt);
            }
        });
        jCadastro.add(jCadastroQuartos);

        jCadastroClientes.setText("Clientes");
        jCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroClientesActionPerformed(evt);
            }
        });
        jCadastro.add(jCadastroClientes);

        jCadastroFuncionarios.setText("Funcionarios");
        jCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroFuncionariosActionPerformed(evt);
            }
        });
        jCadastro.add(jCadastroFuncionarios);

        jMenuBar1.add(jCadastro);

        jAlterar.setText("Alterar");
        jAlterar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jAlterarQuartos.setText("Quartos");
        jAlterarQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarQuartosActionPerformed(evt);
            }
        });
        jAlterar.add(jAlterarQuartos);

        jAlterarClientes.setText("Clientes");
        jAlterarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarClientesActionPerformed(evt);
            }
        });
        jAlterar.add(jAlterarClientes);

        jAlterarFuncionarios.setText("Funcionarios");
        jAlterarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarFuncionariosActionPerformed(evt);
            }
        });
        jAlterar.add(jAlterarFuncionarios);

        jMenuBar1.add(jAlterar);

        jRemover.setText("Remover");
        jRemover.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jRemoverQuartos.setText("Quartos");
        jRemoverQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoverQuartosActionPerformed(evt);
            }
        });
        jRemover.add(jRemoverQuartos);

        jRemoverClientes.setText("Clientes");
        jRemoverClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoverClientesActionPerformed(evt);
            }
        });
        jRemover.add(jRemoverClientes);

        jRemoverFuncionarios.setText("Funcionario");
        jRemoverFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoverFuncionariosActionPerformed(evt);
            }
        });
        jRemover.add(jRemoverFuncionarios);

        jMenuBar1.add(jRemover);

        jListar.setText("Listar");
        jListar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jListarQuartos.setText("Quartos");
        jListarQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListarQuartosActionPerformed(evt);
            }
        });
        jListar.add(jListarQuartos);

        jListarClientes.setText("Clientes");
        jListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListarClientesActionPerformed(evt);
            }
        });
        jListar.add(jListarClientes);

        jListarFuncionarios.setText("Funcionarios");
        jListarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListarFuncionariosActionPerformed(evt);
            }
        });
        jListar.add(jListarFuncionarios);

        jQuartosVazios.setText("Quartos Vazios");
        jQuartosVazios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuartosVaziosActionPerformed(evt);
            }
        });
        jListar.add(jQuartosVazios);

        jQuartoOcupado.setText("Quartos Ocupados");
        jQuartoOcupado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuartoOcupadoActionPerformed(evt);
            }
        });
        jListar.add(jQuartoOcupado);

        jListaCheckIn.setText("Check-in");
        jListaCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListaCheckInActionPerformed(evt);
            }
        });
        jListar.add(jListaCheckIn);

        jMenuBar1.add(jListar);

        jCheckin.setText("Check-in");
        jCheckin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jCheckin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckinMouseClicked(evt);
            }
        });
        jMenuBar1.add(jCheckin);

        jCheckout.setText("Check-out");
        jCheckout.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(jCheckout);

        jSobre.setText("Sobre");
        jSobre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jSobre);

        jSair.setText("Sair");
        jSair.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSairMouseClicked(evt);
            }
        });
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListarQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarQuartosActionPerformed
        new ViewQuarto().listar();
        //JOptionPane.showMessageDialog(null,quartos,"Listar quartos",JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_jListarQuartosActionPerformed

    private void jCadastroQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroQuartosActionPerformed
        View quarto=new ViewQuarto();
        quarto.cadastra();

    }//GEN-LAST:event_jCadastroQuartosActionPerformed

    private void jCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroClientesActionPerformed
        View v=new ViewCliente();
        v.cadastra();

    }//GEN-LAST:event_jCadastroClientesActionPerformed

    private void jSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSobreMouseClicked
        JOptionPane.showMessageDialog(null, "Software desenvolvido como projeto final da disciplina\nSIN 141 - Computação Orienteda a Objetos\n"
                + "O sistema garante o genrenciamento das entradas e saidas de um Hotel.\n\n"
                + "\n"
                + "Breno Figueiredo - 2743\n"
                + "Lucas Batista - 2712\n"
                + "Weslley Rocha - 2706\n"
                + "\n...\n\n"
                + "\n\n...\n\n"
                + "Is Compiling? \n"
                + "Is Working? \n"
                + "Then It Is Thirty! \n"
                + " 三十");
    }//GEN-LAST:event_jSobreMouseClicked

    private void jCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroFuncionariosActionPerformed

       new ViewFuncionario().cadastra();

    }//GEN-LAST:event_jCadastroFuncionariosActionPerformed

    private void jListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarClientesActionPerformed
        View v=new ViewCliente();
        v.listar();
        //JOptionPane.showMessageDialog(null, this.getCliente(), "Listar Clientes", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_jListarClientesActionPerformed

    private void jListarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarFuncionariosActionPerformed
        new ViewFuncionario().listar();
    }//GEN-LAST:event_jListarFuncionariosActionPerformed

    private void jSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSairMouseClicked
      
        int op = JOptionPane.showConfirmDialog(null, "Voce realmente deseja sair do programa? E deseja salvar as alterações?");
        if (op == 0) {
            new Persistence().exporta();
            
            System.exit(0);
        }
    }//GEN-LAST:event_jSairMouseClicked

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jSairActionPerformed

    private void jRemoverQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoverQuartosActionPerformed
        View quarto=new ViewQuarto();
        quarto.remove();
    }//GEN-LAST:event_jRemoverQuartosActionPerformed

    private void jRemoverClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoverClientesActionPerformed
        View v=new ViewCliente();
        v.remove();
    }//GEN-LAST:event_jRemoverClientesActionPerformed

    private void jCheckinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckinMouseClicked
       ViewCheckIn vci=new ViewCheckIn();
       vci.cadastra();
    }//GEN-LAST:event_jCheckinMouseClicked

    private void jRemoverFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoverFuncionariosActionPerformed
        new ViewFuncionario().remove();
    }//GEN-LAST:event_jRemoverFuncionariosActionPerformed

    private void jAlterarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarClientesActionPerformed
        View cliente=new ViewCliente();
        cliente.alterar();
    }//GEN-LAST:event_jAlterarClientesActionPerformed

    private void jAlterarQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarQuartosActionPerformed
        View quarto=new ViewQuarto();
        quarto.alterar();
    }//GEN-LAST:event_jAlterarQuartosActionPerformed

    private void jCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckoutMouseClicked
       ViewCheckOut v=new ViewCheckOut();
       v.start();
    }//GEN-LAST:event_jCheckoutMouseClicked

    private void jQuartosVaziosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuartosVaziosActionPerformed
       new ViewQuarto().listarQuartosLivres();
    }//GEN-LAST:event_jQuartosVaziosActionPerformed

    private void jListaCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListaCheckInActionPerformed
        new ViewCheckIn().listar();
    }//GEN-LAST:event_jListaCheckInActionPerformed

    private void jQuartoOcupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuartoOcupadoActionPerformed
        new ViewQuarto().listarQuartosOcupados();
    }//GEN-LAST:event_jQuartoOcupadoActionPerformed

    private void jAlterarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarFuncionariosActionPerformed
        View funcionario=new ViewFuncionario();
        funcionario.alterar();
    }//GEN-LAST:event_jAlterarFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jAlterar;
    private javax.swing.JMenuItem jAlterarClientes;
    private javax.swing.JMenuItem jAlterarFuncionarios;
    private javax.swing.JMenuItem jAlterarQuartos;
    private javax.swing.JMenu jCadastro;
    private javax.swing.JMenuItem jCadastroClientes;
    private javax.swing.JMenuItem jCadastroFuncionarios;
    private javax.swing.JMenuItem jCadastroQuartos;
    private javax.swing.JMenu jCheckin;
    private javax.swing.JMenu jCheckout;
    private javax.swing.JMenuItem jListaCheckIn;
    private javax.swing.JMenu jListar;
    private javax.swing.JMenuItem jListarClientes;
    private javax.swing.JMenuItem jListarFuncionarios;
    private javax.swing.JMenuItem jListarQuartos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jQuartoOcupado;
    private javax.swing.JMenuItem jQuartosVazios;
    private javax.swing.JMenu jRemover;
    private javax.swing.JMenuItem jRemoverClientes;
    private javax.swing.JMenuItem jRemoverFuncionarios;
    private javax.swing.JMenuItem jRemoverQuartos;
    private javax.swing.JMenu jSair;
    private javax.swing.JMenu jSobre;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cliente
     */
    public ClienteController getCliente() {
        return cliente;
    }

    /**
     * @param cliente the cliente to set
     */
    public void setCliente(ClienteController cliente) {
        this.cliente = cliente;
    }
    public FuncionarioController getFuncionario() {
        return Principal.funcionario;
    }

    public void setFuncionario(FuncionarioController funcionario) {
        Principal.funcionario = funcionario;
    }
}
